[workspace]
resolver = "2"
members = ["core", "npm/native"]
default-members = ["core"]

[workspace.package]
edition = "2024"
version = "0.1.1"
readme = "README.md"
rust-version = "1.85.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pid7-org/ashwa"
keywords = ["ashwa", "memmem", "substring", "find", "search"]
categories = ["algorithms", "hardware-support", "no-std::no-alloc"]
description = "Hardware accelerated routines for single substring search"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
incremental = false

[profile.profile]
debug = true
lto = "off"
strip = "none"
opt-level = 2
codegen-units = 1
inherits = "release"
overflow-checks = false
debug-assertions = false

[workspace.dependencies]
criterion = "0.8.2"
