/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Searches for the first occurrence of `needle` in `haystack`.
 *
 * # Arguments
 * * `haystack` - A byte slice (`&[u8]`) to search within.
 * * `needle` - The byte (`u8`) to find.
 *
 * # Returns
 * * `Some(index)` - The 0-based byte index of the first match.
 * * `None` - If `needle` is not found.
 */
export declare function searchOne(haystack: Uint8Array, needle: number): number | null

/**
 * Searches for the first occurrence of a two-byte `needle` in `haystack`.
 *
 * # Arguments
 * * `haystack` - A byte slice (`&[u8]`) to search within.
 * * `needle` - A 2-byte slice (`&[u8]`) to locate.
 *
 * # Returns
 * * `Some(index)` - The 0-based byte index of the first match.
 * * `None` - If `needle` is not found.
 */
export declare function searchTwo(haystack: Uint8Array, needle: Uint8Array): number | null
