[package]
name = "ashwa"
publish = true
readme = { workspace = true }
edition = { workspace = true }
version = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
description = { workspace = true }
rust-version = { workspace = true }

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
additional-targets = ["i686-apple-darwin"]
targets = [
    "aarch64-apple-darwin",
    "i686-pc-windows-msvc",
    "x86_64-pc-windows-msvc",
    "aarch64-unknown-linux-gnu",
]

[dev-dependencies]
criterion = {workspace = true}

[[bench]]
name = "one_throughput"
harness = false
