name: Publish & Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  lints:
    env:
      RUSTFLAGS: "-D warnings"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            rustflags: "-C target-feature=+avx2,+sse2 --cfg forced_swar_backend"
          - os: ubuntu-24.04-arm
            arch: aarch64
            rustflags: "-C target-feature=+neon --cfg forced_swar_backend"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: rust-${{ runner.os }}-${{ matrix.arch }}-stable

      - name: check (${{ matrix.arch }})
        run: RUSTFLAGS="${{matrix.rustflags}}" cargo check --workspace --all-targets --all-features --tests --benches --examples

  publish:
    name: Publish Packages
    needs: lints
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Authenticate with crates.io
        uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Dry Run — crates.io
        run: cargo publish --dry-run --locked

      - name: Dry Run — npm
        working-directory: npm
        run: npm publish --dry-run --access public

      - name: Publish — crates.io
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Publish — npm
        working-directory: npm
        run: npm publish --access public

  release:
    name: GitHub Release
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Read CHANGELOG
        id: changelog
        shell: bash
        run: |
          body=$(awk '
            /^## / {
              if (seen) exit
              seen=1
            }
            seen
          ' CHANGELOG.md)

          {
            echo 'body<<EOF'
            echo "$body"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release of ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.body }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
