name: Tests

on:
  workflow_dispatch:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  lints:
    env:
      RUSTFLAGS: "-D warnings"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            rustflags: "-C target-feature=+avx2,+sse2 --cfg forced_swar_backend"
          - os: ubuntu-24.04-arm
            arch: aarch64
            rustflags: "-C target-feature=+neon --cfg forced_swar_backend"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: rust-${{ runner.os }}-${{ matrix.arch }}-stable

      - name: check (${{ matrix.arch }})
        run: RUSTFLAGS="${{matrix.rustflags}}" cargo check --workspace --all-targets --all-features --tests --benches --examples

  x86_64:
    needs: lints
    env:
      RUSTFLAGS: "-D warnings"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: rust-ubuntu-latest-x86-64-stable

      - name: SWAR
        run: RUSTFLAGS="--cfg forced_swar_backend" cargo test -- --nocapture

      - name: SSE2
        run: RUSTFLAGS="-C target-feature=+sse2" cargo test -- --nocapture

      - name: AVX2
        run: RUSTFLAGS="-C target-feature=+avx2" cargo test -- --nocapture

  aarch64:
    needs: lints
    env:
      RUSTFLAGS: "-D warnings"
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: rust-ubuntu-24.04-arm-aarch64-stable

      - name: SWAR
        run: RUSTFLAGS="--cfg forced_swar_backend" cargo test -- --nocapture

      - name: NEON
        run: RUSTFLAGS="-C target-feature=+neon" cargo test -- --nocapture

  x86_32:
    needs: lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: rust-ubuntu-latest-i686-stable

      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cross
          git: https://github.com/cross-rs/cross

      - name: SWAR
        run: RUSTFLAGS="--cfg forced_swar_backend" cross test --target i686-unknown-linux-gnu -- --nocapture

      - name: SSE2
        run: RUSTFLAGS="-C target-feature=+sse2" cross test --target i686-unknown-linux-gnu -- --nocapture

  armv7:
    needs: lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          key: rust-ubuntu-latest-armv7-stable

      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cross
          git: https://github.com/cross-rs/cross

      - name: SWAR
        run: RUSTFLAGS="--cfg forced_swar_backend" cross test --target armv7-unknown-linux-gnueabihf -- --nocapture

      - name: NEON
        run: RUSTFLAGS="-C target-feature=+neon" cross test --target armv7-unknown-linux-gnueabihf -- --nocapture

  wasm32:
    needs: lints
    runs-on: ubuntu-latest
    env:
      CARGO_TARGET_WASM32_WASIP2_RUNNER: wasmtime
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasip2

      - uses: Swatinem/rust-cache@v2
        with:
          key: rust-ubuntu-latest-wasm32-stable

      - uses: baptiste0928/cargo-install@v3
        with:
          crate: wasmtime-cli

      - name: SWAR
        run: RUSTFLAGS="--cfg forced_swar_backend" cargo test --target wasm32-wasip2 -- --nocapture

      - name: SIMD128
        run: RUSTFLAGS="-C target-feature=+simd128" cargo test --target wasm32-wasip2 -- --nocapture

  npm-native:
    needs: lints
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "x64 (Linux)"
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: x64
            node_version: 22

          - name: "AArch64 (Linux)"
            os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            arch: arm64
            node_version: 22

          - name: "AArch64 (Macos)"
            os: macos-latest
            target: aarch64-apple-darwin
            arch: arm64
            node_version: 22

          - name: "x64 (Windows 11)"
            os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x64
            node_version: 22

          - name: "AArch64 (Windows 11)"
            os: windows-11-arm
            target: aarch64-pc-windows-msvc
            arch: arm64
            node_version: 22
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.arch }}
          cache: "npm"
          cache-dependency-path: npm/package.json

      - uses: Swatinem/rust-cache@v2
        with:
          key: rust-${{ runner.os }}-${{ matrix.target }}-npm-native

      - name: Install dependencies & build native addon
        run: |
          cd npm
          npm ci || npm install
          cd native
          npx napi build --platform --release --target ${{ matrix.target }}

      - name: Run NPM Native tests
        run: |
          cd npm
          npm run test:node

  npm-wasm32:
    needs: lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: npm/package.json

      - uses: Swatinem/rust-cache@v2
        with:
          key: rust-ubuntu-latest-npm-wasm-stable

      - name: Cache wasm-pack
        id: cache-wasm-pack
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/wasm-pack
          key: wasm-pack-${{ runner.os }}-v0.13.1

      - name: Install wasm-pack
        if: steps.cache-wasm-pack.outputs.cache-hit != 'true'
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Cache Playwright Browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('npm/package.json') }}

      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: |
          cd npm
          npx playwright install chromium

      - name: Install dependencies & build WASM package
        run: |
          cd npm
          npm ci || npm install
          npm run build:wasm

      - name: Run WASM Node & Headless Browser tests
        run: |
          cd npm
          npm run test:wasm

      - name: Run WASM Headless Browser Unit Tests (wasm-pack test)
        run: |
          cd npm/wasm
          RUSTFLAGS="-C target-feature=+simd128" wasm-pack test --chrome --headless
